apiVersion: v1
kind: Service
metadata:
  name: ${jarName}
  labels:
    serviceName: ${jarName}
    tag: ${tag}
spec:
  ports:
    - name: ${portName}
      port: ${port}
      targetPort: ${port}
  selector:
    serviceName: ${jarName}
