apiVersion: v1
kind: Service
metadata:
  name: info-community-service
  labels:
    name: info-community-service
    version: v1
spec:
  ports:
  - port: 8802
    targetPort: 8802
  selector:
    name: info-community-service
