apiVersion: v1
kind: Service
metadata:
  name: info-store-service
  labels:
    name: info-store-service
    version: v1
spec:
  ports:
  - port: 8807
    targetPort: 8807
  selector:
    name: info-store-service
