apiVersion: v1
kind: Service
metadata:
  name: info-admin
  labels:
    name: info-admin
    version: v1
spec:
  ports:
    - port: 7777
      targetPort: 7777
  selector:
    name: info-admin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-admin
  labels:
    name: info-admin
spec:
  selector:
    matchLabels:
      name: info-admin
  replicas: 1
  template:
    metadata:
      labels:
        name: info-admin
    spec:
      containers:
      - name: info-admin
        image: reg.test.local/library/info-admin:0.0.1-SNAPSHOT
      imagePullSecrets:
        - name: registry-secret
