apiVersion: v1
kind: Service
metadata:
  name: info-ad-service
  labels:
    name: info-ad-service
    version: v1
spec:
  ports:
  - port: 8801
    targetPort: 8801
  selector:
    name: info-ad-service
