apiVersion: v1
kind: Service
metadata:
  name: info-hotel-service
  labels:
    name: info-hotel-service
    version: v1
spec:
  ports:
  - port: 8804
    targetPort: 8804
  selector:
    name: info-hotel-service
