apiVersion: v1
kind: Service
metadata:
  name: info-nearby-service
  labels:
    name: info-nearby-service
    version: v1
spec:
  ports:
  - port: 8805
    targetPort: 8805
  selector:
    name: info-nearby-service
