apiVersion: v1
kind: Service
metadata:
  name: info-payment-service
  labels:
    name: info-payment-service
    version: v1
spec:
  ports:
  - port: 8808
    targetPort: 8808
  selector:
    name: info-payment-service
