apiVersion: v1
kind: Service
metadata:
  name: info-groupon-service
  labels:
    name: info-groupon-service
    version: v1
spec:
  ports:
  - port: 8803
    targetPort: 8803
  selector:
    name: info-groupon-service
