apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-gateway
  labels:
    name: info-gateway
spec:
  selector:
    matchLabels:
      name: info-gateway
  replicas: 1
  template:
    metadata:
      labels:
        name: info-gateway
    spec:
      containers:
      - name: info-gateway
        image: reg.test.local/library/info-gateway:0.0.1-SNAPSHOT
      imagePullSecrets:
      - name: registry-secret
