apiVersion: v1
kind: Service
metadata:
  name: info-agent-service
  labels:
    name: info-agent-service
    version: v1
spec:
  ports:
  - port: 8809
    targetPort: 8809
  selector:
    name: info-agent-service
