apiVersion: v1
kind: Service
metadata:
  name: info-news-service
  labels:
    name: info-news-service
    version: v1
spec:
  ports:
    - port: 8806
      targetPort: 8806
  selector:
    name: info-news-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-news-service
  labels:
    name: info-news-service
spec:
  selector:
    matchLabels:
      name: info-news-service
  replicas: 1
  template:
    metadata:
      labels:
        name: info-news-service
    spec:
      containers:
      - name: info-news-service
        image: reg.test.local/library/info-news-service:0.0.1-SNAPSHOT
      imagePullSecrets:
        - name: registry-secret
